name: Aprimo/SharePoint Deployment Pipeline

# Configure workflow retention (days)
env:
  LOG_RETENTION_DAYS: 30
  ARTIFACT_RETENTION_DAYS: 90

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  validate-build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    # Job-specific retention override
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MAVEN_OPTS: -Dhttps.protocols=TLSv1.2

    steps:
      # ========== SETUP ==========
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for version tagging
          persist-credentials: false

      # ========== ENVIRONMENT VALIDATION ==========
      - name: Validate environment
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "::error file=pom.xml::Maven POM file not found!"
            exit 1
          fi
          
          REQUIRED_VARS=(
            "SHAREPOINT_CLIENT_SECRET"
            "APRIMO_CLIENT_SECRET"
          )
          
          for var in "${REQUIRED_VARS[@]}"; do
            if [ -z "${!var}" ]; then
              echo "::error::Missing required environment variable: $var"
              exit 1
            fi
          done

      # ========== BUILD ==========
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Dependency caching

      - name: Build with Maven
        id: build
        run: |
          mvn -B clean package -DskipTests=true
          JAR_PATH=$(ls target/*.jar)
          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT
          echo "build_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      # ========== ARTIFACT HANDLING ==========
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: ${{ steps.build.outputs.jar_path }}
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      # ========== DEPLOYMENT ==========
      - name: Deploy to Aprimo
        if: success()
        env:
          APRIMO_UPLOAD_TOKEN: ${{ secrets.APRIMO_UPLOAD_TOKEN }}
        run: |
          # Example deployment command - replace with your actual logic
          curl -X POST \
            -H "Authorization: Bearer $APRIMO_CLIENT_SECRET" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"${{ steps.build.outputs.jar_path }}" \
            "$APRIMO_UPLOAD_URL/upload?classificationId=$APRIMO_CLASSIFICATION_ID"

      - name: Sync with SharePoint
        if: success()
        run: |
          # Example SharePoint integration
          python scripts/sharepoint_sync.py \
            --site "$SHAREPOINT_SITE_NAME" \
            --drive "$SHAREPOINT_DRIVE_ID" \
            --file "${{ steps.build.outputs.jar_path }}" \
            --version "${{ steps.build.outputs.build_version }}"

      # ========== LOG MANAGEMENT ==========
      - name: Archive full logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: workflow-logs-${{ github.run_id }}
          path: |
            ${{ github.workflow }}-${{ github.run_id }}.log
            maven-build.log
          retention-days: ${{ env.LOG_RETENTION_DAYS }}

      # ========== NOTIFICATIONS ==========
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Deployment failed in run ${{ github.run_id }}`
            })

# ========== WORKFLOW RETENTION SETTINGS ==========
# Repository-level settings (override in repository settings)
# These are defaults - actual retention is min(repository, workflow)
retention:
  logs: ${{ env.LOG_RETENTION_DAYS }}
  artifacts: ${{ env.ARTIFACT_RETENTION_DAYS }}
  deployments: 90
